import pymysql
import getpass

user = input('SQL USER:')
passwd = getpass.getpass('SQL PASSWORD:')
conn = pymysql.connect(host='localhost',
                       user='%s' % user,
                       passwd='%s' % passwd,
                       db='wikipedia',
                       charset='utf8mb4')
cur = conn.cursor()
print ('1:Create tables')
print ('2:Drop tables')
print ('3:Truncate tables')
print ('4:Search')
print ('0:Exit')
num = int(input('I want to: '))
table_list = ['English',
'Achinese',
'Adyghe',
'Afrikaans',
'Akan',
'Alemannisch',
'Amharic',
'Old English',
'Abkhazian',
'Arabic',
'Aragonese',
'Aramaic',
'Aromanian',
'Arpitan',
'Assamese',
'Asturian',
'Guarani',
'Avaric',
'Aymara',
'Azerbaijani',
'تۆرکجه',
'Bambara',
'Bangla',
'Banjar',
'Chinese (Min Nan)',
'Basa Banyumasan',
'Bashkir',
'Belarusian',
'беларуская (тарашкевіца)‎',
'भोजपुरी',
'Bikol Central',
'Bislama',
'Bulgarian',
'Bavarian',
'Tibetan',
'Bosnian',
'Breton',
'буряад',
'Catalan',
'Chuvash',
'Cebuano',
'Czech',
'Chamorro',
'Chavacano de Zamboanga',
'Shona',
'Corsican',
'Welsh',
'Danish',
'Pennsylvania German',
'German',
'Divehi',
'Lower Sorbian',
'Estonian',
'Greek',
'Emiliano-Romagnolo',
'Erzya',
'Spanish',
'Esperanto',
'Extremaduran',
'Basque',
'Persian',
'Faroese',
'French',
'Western Frisian',
'Fulah',
'Friulian',
'Irish',
'Manx',
'Gagauz',
'Scottish Gaelic',
'Galician',
'Gan Chinese',
'Kikuyu',
'Gilaki',
'Gujarati',
'Gothic',
'Goan Konkani',
'Hakka Chinese',
'Kalmyk',
'Korean',
'Hausa',
'Hawaiian',
'Armenian',
'Hindi',
'Upper Sorbian',
'Croatian',
'Ido',
'Igbo',
'Iloko',
'Bishnupriya',
'Indonesian',
'Interlingua',
'Interlingue',
'Inuktitut',
'Inupiaq',
'Ossetic',
'Xhosa',
'Zulu',
'Icelandic',
'Italian',
'Hebrew',
'Javanese',
'Kalaallisut',
'Kannada',
'Pampanga',
'Karachay-Balkar',
'Georgian',
'Kashmiri',
'Kashubian',
'Kazakh',
'Cornish',
'Swahili',
'Haitian Creole',
'Kurdish',
'Kyrgyz',
'Western Mari',
'Ladino',
'лакку',
'Lezghian',
'Lao',
'Northern Luri',
'Latgalian',
'Latin',
'Latvian',
'Luxembourgish',
'Lithuanian',
'Ligurian',
'Limburgish',
'Lingala',
'Livvi-Karelian',
'Lojban',
'Ganda',
'Lombard',
'Hungarian',
'Maithili',
'Macedonian',
'Malagasy',
'Malayalam',
'Maltese',
'Maori',
'Marathi',
'Mingrelian',
'Egyptian Arabic',
'Mazanderani',
'Malay',
'Minangkabau',
'Min Dong Chinese',
'Mirandese',
'Moksha',
'молдовеняскэ',
'Mongolian',
'Burmese',
'Nāhuatl',
'Nauru',
'Dutch',
'Low Saxon',
'Nepali',
'Newari',
'Japanese',
'Neapolitan',
'Chechen',
'Northern Frisian',
'Norfuk / Pitkern',
'Norwegian',
'Norwegian Nynorsk',
'Nouormand',
'Novial',
'Occitan',
'Eastern Mari',
'Odia',
'Ndonga',
'Uzbek',
'Punjabi',
'Pali',
'Palatine German',
'Pangasinan',
'Western Punjabi',
'Papiamento',
'Pashto',
'Jamaican Creole English',
'Komi-Permyak',
'Khmer',
'Picard',
'Piedmontese',
'Tok Pisin',
'Low German',
'Polish',
'Pontic',
'Portuguese',
'Afar',
'Kara-Kalpak',
'Crimean Turkish',
'Tahitian',
'Colognian',
'Romanian',
'Romani',
'Romansh',
'Quechua',
'Rusyn',
'Russian',
'Sakha',
'Northern Sami',
'Samoan',
'Sanskrit',
'Sango',
'Sardinian',
'Scots',
'Saterland Frisian',
'Northern Sotho',
'Tswana',
'Albanian',
'Sicilian',
'Sinhala',
'Simple English',
'Sindhi',
'Swati',
'Slovak',
'Slovenian',
'Church Slavic',
'Silesian',
'Somali',
'Central Kurdish',
'Sranan Tongo',
'Serbian',
'Serbo-Croatian',
'Sundanese',
'Finnish',
'Swedish',
'Tagalog',
'Tamil',
'Kabyle',
'tarandíne',
'Tatar',
'Telugu',
'Tetum',
'Thai',
'Tigrinya',
'Tajik',
'Cherokee',
'Cheyenne',
'Venda',
'Turkish',
'Turkmen',
'Twi',
'Tuvinian',
'Udmurt',
'Buginese',
'Ukrainian',
'Urdu',
'Uyghur',
'Zhuang',
'Venetian',
'Veps',
'Vietnamese',
'Volapük',
'Võro',
'Walloon',
'Classical Chinese',
'West Flemish',
'Waray',
'Wolof',
'Wu Chinese',
'Tsonga',
'Yiddish',
'Yoruba',
'Cantonese',
'Zazaki',
'Zeelandic',
'Samogitian',
'Chinese',
'Fiji Hindi',
'Cree',
'Oromo',
'Kabardian',
'Tumbuka',
'Kinyarwanda',
'Navajo',
'Wektor',
'Komi',
'Kongo',
'Southern Sotho',
'Nyanja',
'Ewe',
'Fijian',
'Tongan',
'Dzongkha',
'Sichuan Yi',
'Rundi',
'Tulu',
'Persona',
'Choctaw',
'Hiri Motu',
'Kuanyama',
'Belarusian (Taraškievica orthography)',
'Marshallese']


while num != 0:
    if num == 1:
        cur.execute('CREATE TABLE English(English_id INT NOT NULL AUTO_INCREMENT, English VARCHAR(255) NOT NULL, Flag INT DEFAULT "0", PRIMARY KEY (English_id)) CHARSET=utf8mb4')
        for i in table_list[1:]:
            cur.execute('CREATE TABLE `' + i + '`(`' + i + '_id` INT NOT NULL AUTO_INCREMENT, `'
                + i + '` VARCHAR(255) NOT NULL, English_id INT NOT NULL, PRIMARY KEY (`' + i + '_id`), FOREIGN KEY(English_id) REFERENCES English(English_id)) CHARSET=utf8mb4'
                )
    if num == 2:
        for i in table_list:
            cur.execute('DROP TABLE `' + i + '`')
    if num == 3:
        for i in table_list:
            cur.execute('TRUNCATE TABLE `' + i + '`')
    if num == 4:
        key_word = str(input('Search:'))
        dictionary = {}
        cur.execute('SELECT * FROM ENGLISH WHERE ENGLISH = "' + key_word +'"')
        for item in cur:
            dictionary['English'] = item[1]
            English_id = str(item[0])
        for item in table_list[1:]:
            cur.execute('SELECT * FROM `' + item + '` WHERE English_id = "' + English_id + '"')
            for i in cur:
                dictionary[item] = str(i[1])
        for item in dictionary:
            print (item + ':' + dictionary[item])
        dictionary.clear()
    conn.commit() 
    num = int(input('I want to:'))
cur.close()
conn.close()
print ('finish')